label START
	if var ch1.temp_ending_1_12_leg_ready jump JUST_TEXT
	choice "Check inside the cauldron?"
		"Yes"
			fade out
			pause 2
			"A boy's body rests at the bottom of the cauldron. It's missing a leg."
			hide ui
			set ch1.temp_ending_1_12_leg_ready = true
			pause 2
			action turn down
			fade in
		"No"
			end
	end

label JUST_TEXT
	"A boy's body with a missing leg rests at the bottom of the cauldron."
