label START
    if var ch1.forest_lockedsite_unlocked
        "There's no reason to do that."
        end
    fade out
    set ch1.forest_lockedsite_unlocked = true
    objective fail ch1.locked_site_keys
    pause 1
    audio sfx play snap
    pause 1
    audio sfx play chainlink
    pause 1.5
    set ch1.forest_lockedsite_open = true
    system refresh
    audio sfx play gate
    pause 1
    fade in
    end
