label START
    if repeat jump AGAIN
    lacie "This vent is suspicious."
    if var ch1.facility_dungeon_1_checked_exit
        lacie "Maybe I could escape through here?" mood thinking3
    if not var ch1.facility_dungeon_1_checked_exit
        lacie "It's almost like it's inviting me in." mood blank2
    set ch1.facility_dungeon_seen_vent = true
    end

label AGAIN
    "It's too high to reach."
    end
