label START
    if not var general.blackpass_red_item_3_spawned end
    if var general.blackpass_red_item_3_took end
    choice "Pick up ${item:global.reditem_3}?"
        "Yes"
            continue
        "No"
            end
    item add global.reditem_3
    set general.blackpass_red_item_3_spawned = false
    set general.blackpass_red_item_3_took = true
    set general.blackpass_red_items ++
    end
