label START
    if item ch1.mk_compress_activated jump ALREADY_DONE
    item remove ch1.mk_compress
    fade out
    pause 1
    "You soak the rag in the pool..." background none
    hide ui
    pause 1
    audio sfx play swish
    pause 0.2
    fade flash color white
    pause 1
    item add ch1.mk_compress_activated
    event call ch1_event_mk_check_items
    fade in
    end

label ALREADY_DONE
    "It's already wet enough."
    end
