label START
	if var general.chapter == 1
		if var general.inbetween
			if not var ch1.home_seen_alarm
				audio ambiance play alarm
				bubble exclamation_silent
				pause 0.5
				lacie "..." mood bothered
				move to Ch1_Home_2F_Bedroom_A point alarm
				audio sfx play alarm_click
				audio ambiance stop time 0
				set ch1.home_seen_alarm = true
				end
	audio sfx play door
	move to Ch1_Home_2F_Hallway point bedroom_a_door
