label START
	if var ch1.mk_seen_blessing_1 end
	set ch1.mk_seen_blessing_1 = true
	pause 1
	fade out
	audio bgm volume 0
	pause 1
	"The [color=#90EE90]first[/color] blessing..." format center position center background none
	"\"What I [color=#CD5C5C]saw[/color] in the [color=#CD5C5C]mirror[/color] was uglier than I had hoped.\"" format center position center background none
	pause 1
	fade in
	audio bgm volume 1
	pause 0.5
