label START
    if var ch1.mk_seen_blessing_5 end
    set ch1.mk_seen_blessing_5 = true
    pause 1
    fade out
    audio bgm volume 0
    pause 1
    "The [color=#90EE90]fifth[/color] blessing..." format center position center background none
    "\"There are so many things a knife can [color=#CD5C5C]cut[/color] through.\"" format center position center background none
    pause 1
    fade in
    audio bgm volume 0
    pause 0.5
