label START
    if var ch1.forest_entrance_south_took_fragment jump STILL
    "A swing set moves eerily, though there's no wind."
    "There's something underneath..."
    choice "Take ${item:ch1.doorknob_library_fragment}?"
        "Yes"
            continue
        "No"
            end
    set ch1.forest_entrance_south_took_fragment = true
    system refresh
    item add ch1.doorknob_library_fragment
    end

label STILL
    "It stopped moving."
