label START
	if var general.chapter == 1 jump CH1 else jump MOVE

label CH1
	if var ch1.home_ritualstarted
		if var general.part_of_day == "evening"
			audio bgm stop time 3
			audio bgm override on ch1_home_investigation_q
			audio bgm play ch1_home_investigation_q
		jump MOVE
	lacie "I've been outside enough for now." mood disappointed2
	end


label MOVE
	audio sfx play door
	move to Ch1_Home_Exterior_Back point backyard_door
