label START
    if var ch1.mk_rescued_sai end
    if var general.serious end
    if repeat end
    chara set lacie at left
    chara set sai at right
    sai "What the hell are you waving that foot around for!?" mood annoyed4
    sai "Did you cut it..?" mood thinking13
    lacie "..." mood concerned
    lacie "I had to." mood concerned2
    sai "Mhmmm..." mood thinking14
    lacie "It's true." mood concerned6
    sai "Yeah..." mood thinking15
    lacie "..." mood bothered
