label START
    if var ch1.mk_rescued_sai end
    if var general.serious end
    if repeat end
    chara set lacie at left
    chara set sai at right
    lacie "Um... could you..." mood blank1
    sai "What? You didn't even help me out of here and you want me to cut myself?" mood annoyed
    sai "Is this how you make friends?" mood blank4
    lacie "..." mood blank2
    lacie "(Joke's on you... I don't make friends.)" mood annoyed4
