label START
    if var ch1.facility_valve_2_set
        event queue event_handle_already_full
        end
    if repeat jump AGAIN
    "You try to fit the handle in the slot..."
    chara set sai at right
    sai "What are you doing? Those shapes don't match." mood blank5
    "The handle fits!"
    sai "...Huh." mood blank6
label AGAIN
    item remove ch1.facility_handle_star
    set ch1.facility_valve_2_set = "star"
    event queue misc_valve_2
