label START
	if var ch1.facility_valve_1_set
		event queue event_handle_already_full
		end
	if repeat jump AGAIN
	"You try to fit the handle in the slot..."
	"The handle fits!"
	chara set lacie at left
	chara set sai at right
	sai "Are you switching them around...?"
	lacie "I'm just trying things."
label AGAIN
	item remove ch1.facility_handle_diamond
	set ch1.facility_valve_1_set = "diamond"
	event queue misc_valve_1
