label START
    "It's a yellow mailbox. There's a letter inside:"
    "\"Dear reader,"
    "Do you wonder who I am?"
    "Do you wonder what this room holds?"
    "It's truly a dream to communicate with you through these letters after my passing."
    "How charming, to have one be intrigued by my words even after my departure."
    "What must you be thinking, I wonder?"
    "What will your last thoughts be, as your vision becomes obstructed with red?\""
    end
