label START
    "It's a yellow mailbox. There's a letter inside:"
    "\"Dear reader,"
    "Unfortunately, I cannot let you proceed much further."
    "You see, my private space is just up ahead."
    "It would be rude to invade my most personal thoughts, despite my regrettable death."
    "But don't worry!"
    "You haven't come for nothing."
    "I'll be using you to keep my dear friend happy.\""
    end
