label START
	"It's a yellow mailbox. There's a letter inside:"
	"\"Dear reader,"
	"Welcome to my room!"
	"If you're reading this, then I must already be dead."
	"And if I, of all people, am dead, it must mean all those poor losers are as well."
	"An indestructible force must have wiped our poor souls."
	"Or possibly, Lilith found a way to ruin everything."
	"Again."
	"Oh, how I would love to rip each of her eyeballs out one by one.\""
	end
