label START
    "It's a yellow mailbox. There's a letter inside:"
    "\"Dear reader,"
    "They always told me I'm a blabbermouth."
    "But with so many things to say, how can I help myself?"
    "Besides, my beautiful words have kept us well fed for centuries, have they not?"
    "They should all be thanking me."
    "Respecting me."
    "Licking the floor I step on until their tongues bleed.\""
    end
